version: "3.9"

services:
  postgres:
    container_name: odachin_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: odachin
    # volumes:
    #   - .docker/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - app-network

  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    container_name: envoy-grpc-proxy
    ports:
      - "9000:9000"

  web:
    container_name: odashin_web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL = "http://127.0.0.1:50051"
    # volumes:
    #   - ./apps/web:/app
    networks:
      - app-network

  backend:
    container_name: odachin_backend
    build:
      context: ./apps/service
      dockerfile: Dockerfile
    tty: true
    restart: always
    ports:
      - "50051:50051"
    # depends_on:
    #   - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/odachin
    # volumes:
    #   - ./apps/backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
