// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/odachin/allowance.proto (package odachin.allowance, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/odachin/allowance.proto.
 */
export const file_v1_odachin_allowance: GenFile = /*@__PURE__*/
  fileDesc("Chp2MS9vZGFjaGluL2FsbG93YW5jZS5wcm90bxIRb2RhY2hpbi5hbGxvd2FuY2UiPAoIQWxsb2FuY2UiMAoEVHlwZRIPCgtFVkVSWV9OX0RBWRAAEgoKBldFRUtMWRABEgsKB01PTlRITFkQAiK2AgoYUmVnaXN0ZXJBbGxvd2FuY2VSZXF1ZXN0EhsKCnRvX3VzZXJfaWQYASABKAlCB7pIBHICEAESHgoGYW1vdW50GAIgASgBQg66SAsSCSEAAAAAAAAAABJBCg1pbnRlcnZhbF90eXBlGAMgASgOMiAub2RhY2hpbi5hbGxvd2FuY2UuQWxsb2FuY2UuVHlwZUIIukgFggECEAESHgoIaW50ZXJ2YWwYBCABKA1CB7pIBBoCKAFIAIgBARIcCgRkYXRlGAUgASgNQgm6SAYaBBgfKAFIAYgBARI2CgtkYXlfb2Zfd2VlaxgGIAEoDjIcLm9kYWNoaW4uYWxsb3dhbmNlLkRheU9mV2Vla0gCiAEBQgsKCV9pbnRlcnZhbEIHCgVfZGF0ZUIOCgxfZGF5X29mX3dlZWsivwIKFlVwZGF0ZUFsbG93YW5jZVJlcXVlc3QSHQoMYWxsb3dhbmNlX2lkGAEgASgEQge6SAQiAigBEiMKBmFtb3VudBgCIAEoAUIOukgLEgkhAAAAAAAAAABIAIgBARI8Cg1pbnRlcnZhbF90eXBlGAMgASgOMiAub2RhY2hpbi5hbGxvd2FuY2UuQWxsb2FuY2UuVHlwZUgBiAEBEhUKCGludGVydmFsGAQgASgNSAKIAQESEQoEZGF0ZRgFIAEoDUgDiAEBEjYKC2RheV9vZl93ZWVrGAYgASgOMhwub2RhY2hpbi5hbGxvd2FuY2UuRGF5T2ZXZWVrSASIAQFCCQoHX2Ftb3VudEIQCg5faW50ZXJ2YWxfdHlwZUILCglfaW50ZXJ2YWxCBwoFX2RhdGVCDgoMX2RheV9vZl93ZWVrKmcKCURheU9mV2VlaxIKCgZNT05EQVkQABILCgdUVUVTREFZEAESDQoJV0VETkVTREFZEAISDAoIVEhVUlNEQVkQAxIKCgZGUklEQVkQBBIMCghTQVRVUkRBWRAFEgoKBlNVTkRBWRAGMsIBChBBbGxvd2FuY2VTZXJ2aWNlElgKEVJlZ2lzdGVyQWxsb3dhbmNlEisub2RhY2hpbi5hbGxvd2FuY2UuUmVnaXN0ZXJBbGxvd2FuY2VSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5ElQKD1VwZGF0ZUFsbG93YW5jZRIpLm9kYWNoaW4uYWxsb3dhbmNlLlVwZGF0ZUFsbG93YW5jZVJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHliBnByb3RvMw", [file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * @generated from message odachin.allowance.Alloance
 */
export type Alloance = Message<"odachin.allowance.Alloance"> & {
};

/**
 * Describes the message odachin.allowance.Alloance.
 * Use `create(AlloanceSchema)` to create a new message.
 */
export const AlloanceSchema: GenMessage<Alloance> = /*@__PURE__*/
  messageDesc(file_v1_odachin_allowance, 0);

/**
 * @generated from enum odachin.allowance.Alloance.Type
 */
export enum Alloance_Type {
  /**
   * n日ごと
   *
   * @generated from enum value: EVERY_N_DAY = 0;
   */
  EVERY_N_DAY = 0,

  /**
   * 毎週
   *
   * @generated from enum value: WEEKLY = 1;
   */
  WEEKLY = 1,

  /**
   * 毎月
   *
   * @generated from enum value: MONTHLY = 2;
   */
  MONTHLY = 2,
}

/**
 * Describes the enum odachin.allowance.Alloance.Type.
 */
export const Alloance_TypeSchema: GenEnum<Alloance_Type> = /*@__PURE__*/
  enumDesc(file_v1_odachin_allowance, 0, 0);

/**
 * @generated from message odachin.allowance.RegisterAllowanceRequest
 */
export type RegisterAllowanceRequest = Message<"odachin.allowance.RegisterAllowanceRequest"> & {
  /**
   * @generated from field: string to_user_id = 1;
   */
  toUserId: string;

  /**
   * @generated from field: double amount = 2;
   */
  amount: number;

  /**
   * @generated from field: odachin.allowance.Alloance.Type interval_type = 3;
   */
  intervalType: Alloance_Type;

  /**
   * @generated from field: optional uint32 interval = 4;
   */
  interval?: number;

  /**
   * @generated from field: optional uint32 date = 5;
   */
  date?: number;

  /**
   * @generated from field: optional odachin.allowance.DayOfWeek day_of_week = 6;
   */
  dayOfWeek?: DayOfWeek;
};

/**
 * Describes the message odachin.allowance.RegisterAllowanceRequest.
 * Use `create(RegisterAllowanceRequestSchema)` to create a new message.
 */
export const RegisterAllowanceRequestSchema: GenMessage<RegisterAllowanceRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_allowance, 1);

/**
 * @generated from message odachin.allowance.UpdateAllowanceRequest
 */
export type UpdateAllowanceRequest = Message<"odachin.allowance.UpdateAllowanceRequest"> & {
  /**
   * @generated from field: uint64 allowance_id = 1;
   */
  allowanceId: bigint;

  /**
   * @generated from field: optional double amount = 2;
   */
  amount?: number;

  /**
   * @generated from field: optional odachin.allowance.Alloance.Type interval_type = 3;
   */
  intervalType?: Alloance_Type;

  /**
   * @generated from field: optional uint32 interval = 4;
   */
  interval?: number;

  /**
   * @generated from field: optional uint32 date = 5;
   */
  date?: number;

  /**
   * @generated from field: optional odachin.allowance.DayOfWeek day_of_week = 6;
   */
  dayOfWeek?: DayOfWeek;
};

/**
 * Describes the message odachin.allowance.UpdateAllowanceRequest.
 * Use `create(UpdateAllowanceRequestSchema)` to create a new message.
 */
export const UpdateAllowanceRequestSchema: GenMessage<UpdateAllowanceRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_allowance, 2);

/**
 * @generated from enum odachin.allowance.DayOfWeek
 */
export enum DayOfWeek {
  /**
   * @generated from enum value: MONDAY = 0;
   */
  MONDAY = 0,

  /**
   * @generated from enum value: TUESDAY = 1;
   */
  TUESDAY = 1,

  /**
   * @generated from enum value: WEDNESDAY = 2;
   */
  WEDNESDAY = 2,

  /**
   * @generated from enum value: THURSDAY = 3;
   */
  THURSDAY = 3,

  /**
   * @generated from enum value: FRIDAY = 4;
   */
  FRIDAY = 4,

  /**
   * @generated from enum value: SATURDAY = 5;
   */
  SATURDAY = 5,

  /**
   * @generated from enum value: SUNDAY = 6;
   */
  SUNDAY = 6,
}

/**
 * Describes the enum odachin.allowance.DayOfWeek.
 */
export const DayOfWeekSchema: GenEnum<DayOfWeek> = /*@__PURE__*/
  enumDesc(file_v1_odachin_allowance, 0);

/**
 * @generated from service odachin.allowance.AllowanceService
 */
export const AllowanceService: GenService<{
  /**
   * @generated from rpc odachin.allowance.AllowanceService.RegisterAllowance
   */
  registerAllowance: {
    methodKind: "unary";
    input: typeof RegisterAllowanceRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.allowance.AllowanceService.UpdateAllowance
   */
  updateAllowance: {
    methodKind: "unary";
    input: typeof UpdateAllowanceRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_odachin_allowance, 0);

