// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/odachin/auth.proto (package odachin.auth, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/odachin/auth.proto.
 */
export const file_v1_odachin_auth: GenFile = /*@__PURE__*/
  fileDesc("ChV2MS9vZGFjaGluL2F1dGgucHJvdG8SDG9kYWNoaW4uYXV0aCKjAQoRQ3JlYXRlVXNlclJlcXVlc3QSGAoHdXNlcl9pZBgBIAEoCUIHukgEcgIQARIVCgRuYW1lGAIgASgJQge6SARyAhABEhYKBWVtYWlsGAMgASgJQge6SARyAmABEhkKCHBhc3N3b3JkGAQgASgJQge6SARyAhAIEioKBHJvbGUYBSABKA4yEi5vZGFjaGluLmF1dGguUm9sZUIIukgFggECEAEiIwoSQ3JlYXRlVXNlclJlc3BvbnNlEg0KBXRva2VuGAEgASgJInsKEVVwZGF0ZVVzZXJSZXF1ZXN0EhEKBG5hbWUYASABKAlIAIgBARISCgVlbWFpbBgCIAEoCUgBiAEBEhoKDXByb2ZpbGVfaW1hZ2UYAyABKAxIAogBAUIHCgVfbmFtZUIICgZfZW1haWxCEAoOX3Byb2ZpbGVfaW1hZ2UiQwoMTG9naW5SZXF1ZXN0EhgKB3VzZXJfaWQYASABKAlCB7pIBHICEAESGQoIcGFzc3dvcmQYAiABKAlCB7pIBHICEAgiHgoNTG9naW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCSIuChJHZXRVc2VySW5mb1JlcXVlc3QSGAoHdXNlcl9pZBgBIAEoCUIHukgEcgIQASKKAQoTR2V0VXNlckluZm9SZXNwb25zZRIPCgd1c2VyX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSIAoEcm9sZRgDIAEoDjISLm9kYWNoaW4uYXV0aC5Sb2xlEh0KEGF2YXRhcl9pbWFnZV91cmwYBCABKAlIAIgBAUITChFfYXZhdGFyX2ltYWdlX3VybCK+AQoSR2V0T3duSW5mb1Jlc3BvbnNlEgwKBG5hbWUYASABKAkSDQoFZW1haWwYAiABKAkSHQoQYXZhdGVyX2ltYWdlX3VybBgDIAEoCUgAiAEBEiAKBHJvbGUYBCABKA4yEi5vZGFjaGluLmF1dGguUm9sZRIPCgd1c2VyX2lkGAUgASgJEhYKCWZhbWlseV9pZBgGIAEoBEgBiAEBQhMKEV9hdmF0ZXJfaW1hZ2VfdXJsQgwKCl9mYW1pbHlfaWQqHQoEUm9sZRIKCgZQQVJFTlQQABIJCgVDSElMRBABMoMDCgtBdXRoU2VydmljZRJPCgpDcmVhdGVVc2VyEh8ub2RhY2hpbi5hdXRoLkNyZWF0ZVVzZXJSZXF1ZXN0GiAub2RhY2hpbi5hdXRoLkNyZWF0ZVVzZXJSZXNwb25zZRJFCgpVcGRhdGVVc2VyEh8ub2RhY2hpbi5hdXRoLlVwZGF0ZVVzZXJSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkAKBUxvZ2luEhoub2RhY2hpbi5hdXRoLkxvZ2luUmVxdWVzdBobLm9kYWNoaW4uYXV0aC5Mb2dpblJlc3BvbnNlElIKC0dldFVzZXJJbmZvEiAub2RhY2hpbi5hdXRoLkdldFVzZXJJbmZvUmVxdWVzdBohLm9kYWNoaW4uYXV0aC5HZXRVc2VySW5mb1Jlc3BvbnNlEkYKCkdldE93bkluZm8SFi5nb29nbGUucHJvdG9idWYuRW1wdHkaIC5vZGFjaGluLmF1dGguR2V0T3duSW5mb1Jlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * @generated from message odachin.auth.CreateUserRequest
 */
export type CreateUserRequest = Message<"odachin.auth.CreateUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: odachin.auth.Role role = 5;
   */
  role: Role;
};

/**
 * Describes the message odachin.auth.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 0);

/**
 * @generated from message odachin.auth.CreateUserResponse
 */
export type CreateUserResponse = Message<"odachin.auth.CreateUserResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message odachin.auth.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 1);

/**
 * @generated from message odachin.auth.UpdateUserRequest
 */
export type UpdateUserRequest = Message<"odachin.auth.UpdateUserRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;

  /**
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * @generated from field: optional bytes profile_image = 3;
   */
  profileImage?: Uint8Array;
};

/**
 * Describes the message odachin.auth.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export const UpdateUserRequestSchema: GenMessage<UpdateUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 2);

/**
 * @generated from message odachin.auth.LoginRequest
 */
export type LoginRequest = Message<"odachin.auth.LoginRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message odachin.auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 3);

/**
 * @generated from message odachin.auth.LoginResponse
 */
export type LoginResponse = Message<"odachin.auth.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message odachin.auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 4);

/**
 * @generated from message odachin.auth.GetUserInfoRequest
 */
export type GetUserInfoRequest = Message<"odachin.auth.GetUserInfoRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message odachin.auth.GetUserInfoRequest.
 * Use `create(GetUserInfoRequestSchema)` to create a new message.
 */
export const GetUserInfoRequestSchema: GenMessage<GetUserInfoRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 5);

/**
 * @generated from message odachin.auth.GetUserInfoResponse
 */
export type GetUserInfoResponse = Message<"odachin.auth.GetUserInfoResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: odachin.auth.Role role = 3;
   */
  role: Role;

  /**
   * @generated from field: optional string avatar_image_url = 4;
   */
  avatarImageUrl?: string;
};

/**
 * Describes the message odachin.auth.GetUserInfoResponse.
 * Use `create(GetUserInfoResponseSchema)` to create a new message.
 */
export const GetUserInfoResponseSchema: GenMessage<GetUserInfoResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 6);

/**
 * @generated from message odachin.auth.GetOwnInfoResponse
 */
export type GetOwnInfoResponse = Message<"odachin.auth.GetOwnInfoResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: optional string avater_image_url = 3;
   */
  avaterImageUrl?: string;

  /**
   * @generated from field: odachin.auth.Role role = 4;
   */
  role: Role;

  /**
   * @generated from field: string user_id = 5;
   */
  userId: string;

  /**
   * @generated from field: optional uint64 family_id = 6;
   */
  familyId?: bigint;
};

/**
 * Describes the message odachin.auth.GetOwnInfoResponse.
 * Use `create(GetOwnInfoResponseSchema)` to create a new message.
 */
export const GetOwnInfoResponseSchema: GenMessage<GetOwnInfoResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_auth, 7);

/**
 * @generated from enum odachin.auth.Role
 */
export enum Role {
  /**
   * 親
   *
   * @generated from enum value: PARENT = 0;
   */
  PARENT = 0,

  /**
   * 子供
   *
   * @generated from enum value: CHILD = 1;
   */
  CHILD = 1,
}

/**
 * Describes the enum odachin.auth.Role.
 */
export const RoleSchema: GenEnum<Role> = /*@__PURE__*/
  enumDesc(file_v1_odachin_auth, 0);

/**
 * @generated from service odachin.auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc odachin.auth.AuthService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
  /**
   * @generated from rpc odachin.auth.AuthService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc odachin.auth.AuthService.GetUserInfo
   */
  getUserInfo: {
    methodKind: "unary";
    input: typeof GetUserInfoRequestSchema;
    output: typeof GetUserInfoResponseSchema;
  },
  /**
   * @generated from rpc odachin.auth.AuthService.GetOwnInfo
   */
  getOwnInfo: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetOwnInfoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_odachin_auth, 0);

