// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/odachin/faimily.proto (package odachin.family, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/odachin/faimily.proto.
 */
export const file_v1_odachin_faimily: GenFile = /*@__PURE__*/
  fileDesc("Chh2MS9vZGFjaGluL2ZhaW1pbHkucHJvdG8SDm9kYWNoaW4uZmFtaWx5IjIKEkNyZWF0ZUdyb3VwUmVxdWVzdBIcCgtmYW1pbHlfbmFtZRgBIAEoCUIHukgEcgIQASIwChFJbnZpdGVVc2VyUmVxdWVzdBIbCgp0b191c2VyX2lkGAEgASgJQge6SARyAhABIjkKF0FjY2VwdEludml0YXRpb25SZXF1ZXN0Eh4KDWludml0YXRpb25faWQYASABKARCB7pIBCICKAEy+AEKDUZhbWlseVNlcnZpY2USSQoLQ3JlYXRlR3JvdXASIi5vZGFjaGluLmZhbWlseS5DcmVhdGVHcm91cFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSRwoKSW52aXRlVXNlchIhLm9kYWNoaW4uZmFtaWx5Lkludml0ZVVzZXJSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5ElMKEEFjY2VwdEludml0YXRpb24SJy5vZGFjaGluLmZhbWlseS5BY2NlcHRJbnZpdGF0aW9uUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eWIGcHJvdG8z", [file_google_protobuf_empty, file_buf_validate_validate]);

/**
 * @generated from message odachin.family.CreateGroupRequest
 */
export type CreateGroupRequest = Message<"odachin.family.CreateGroupRequest"> & {
  /**
   * @generated from field: string family_name = 1;
   */
  familyName: string;
};

/**
 * Describes the message odachin.family.CreateGroupRequest.
 * Use `create(CreateGroupRequestSchema)` to create a new message.
 */
export const CreateGroupRequestSchema: GenMessage<CreateGroupRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 0);

/**
 * @generated from message odachin.family.InviteUserRequest
 */
export type InviteUserRequest = Message<"odachin.family.InviteUserRequest"> & {
  /**
   * @generated from field: string to_user_id = 1;
   */
  toUserId: string;
};

/**
 * Describes the message odachin.family.InviteUserRequest.
 * Use `create(InviteUserRequestSchema)` to create a new message.
 */
export const InviteUserRequestSchema: GenMessage<InviteUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 1);

/**
 * @generated from message odachin.family.AcceptInvitationRequest
 */
export type AcceptInvitationRequest = Message<"odachin.family.AcceptInvitationRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message odachin.family.AcceptInvitationRequest.
 * Use `create(AcceptInvitationRequestSchema)` to create a new message.
 */
export const AcceptInvitationRequestSchema: GenMessage<AcceptInvitationRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 2);

/**
 * @generated from service odachin.family.FamilyService
 */
export const FamilyService: GenService<{
  /**
   * @generated from rpc odachin.family.FamilyService.CreateGroup
   */
  createGroup: {
    methodKind: "unary";
    input: typeof CreateGroupRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.family.FamilyService.InviteUser
   */
  inviteUser: {
    methodKind: "unary";
    input: typeof InviteUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.family.FamilyService.AcceptInvitation
   */
  acceptInvitation: {
    methodKind: "unary";
    input: typeof AcceptInvitationRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_odachin_faimily, 0);

