// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/odachin/faimily.proto (package odachin.family, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Role } from "./auth_pb";
import { file_v1_odachin_auth } from "./auth_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/odachin/faimily.proto.
 */
export const file_v1_odachin_faimily: GenFile = /*@__PURE__*/
  fileDesc("Chh2MS9vZGFjaGluL2ZhaW1pbHkucHJvdG8SDm9kYWNoaW4uZmFtaWx5IoEBCgpGYW1pbHlVc2VyEg8KB3VzZXJfaWQYASABKAkSDAoEbmFtZRgCIAEoCRIdChBhdmF0YXJfaW1hZ2VfdXJsGAMgASgJSACIAQESIAoEcm9sZRgEIAEoDjISLm9kYWNoaW4uYXV0aC5Sb2xlQhMKEV9hdmF0YXJfaW1hZ2VfdXJsIjIKEkNyZWF0ZUdyb3VwUmVxdWVzdBIcCgtmYW1pbHlfbmFtZRgBIAEoCUIHukgEcgIQASIwChFJbnZpdGVVc2VyUmVxdWVzdBIbCgp0b191c2VyX2lkGAEgASgJQge6SARyAhABIjkKF0FjY2VwdEludml0YXRpb25SZXF1ZXN0Eh4KDWludml0YXRpb25faWQYASABKARCB7pIBCICKAEicwoVR2V0RmFtaWx5SW5mb1Jlc3BvbnNlEjIKDmZhbWlseV9tZW1iZXJzGAEgAygLMhoub2RhY2hpbi5mYW1pbHkuRmFtaWx5VXNlchITCgtmYW1pbHlfbmFtZRgCIAEoCRIRCglmYW1pbHlfaWQYAyABKAQyyAIKDUZhbWlseVNlcnZpY2USSQoLQ3JlYXRlR3JvdXASIi5vZGFjaGluLmZhbWlseS5DcmVhdGVHcm91cFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSTgoNR2V0RmFtaWx5SW5mbxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRolLm9kYWNoaW4uZmFtaWx5LkdldEZhbWlseUluZm9SZXNwb25zZRJHCgpJbnZpdGVVc2VyEiEub2RhY2hpbi5mYW1pbHkuSW52aXRlVXNlclJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSUwoQQWNjZXB0SW52aXRhdGlvbhInLm9kYWNoaW4uZmFtaWx5LkFjY2VwdEludml0YXRpb25SZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5YgZwcm90bzM", [file_google_protobuf_empty, file_buf_validate_validate, file_v1_odachin_auth]);

/**
 * @generated from message odachin.family.FamilyUser
 */
export type FamilyUser = Message<"odachin.family.FamilyUser"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string avatar_image_url = 3;
   */
  avatarImageUrl?: string;

  /**
   * @generated from field: odachin.auth.Role role = 4;
   */
  role: Role;
};

/**
 * Describes the message odachin.family.FamilyUser.
 * Use `create(FamilyUserSchema)` to create a new message.
 */
export const FamilyUserSchema: GenMessage<FamilyUser> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 0);

/**
 * @generated from message odachin.family.CreateGroupRequest
 */
export type CreateGroupRequest = Message<"odachin.family.CreateGroupRequest"> & {
  /**
   * @generated from field: string family_name = 1;
   */
  familyName: string;
};

/**
 * Describes the message odachin.family.CreateGroupRequest.
 * Use `create(CreateGroupRequestSchema)` to create a new message.
 */
export const CreateGroupRequestSchema: GenMessage<CreateGroupRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 1);

/**
 * @generated from message odachin.family.InviteUserRequest
 */
export type InviteUserRequest = Message<"odachin.family.InviteUserRequest"> & {
  /**
   * @generated from field: string to_user_id = 1;
   */
  toUserId: string;
};

/**
 * Describes the message odachin.family.InviteUserRequest.
 * Use `create(InviteUserRequestSchema)` to create a new message.
 */
export const InviteUserRequestSchema: GenMessage<InviteUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 2);

/**
 * @generated from message odachin.family.AcceptInvitationRequest
 */
export type AcceptInvitationRequest = Message<"odachin.family.AcceptInvitationRequest"> & {
  /**
   * @generated from field: uint64 invitation_id = 1;
   */
  invitationId: bigint;
};

/**
 * Describes the message odachin.family.AcceptInvitationRequest.
 * Use `create(AcceptInvitationRequestSchema)` to create a new message.
 */
export const AcceptInvitationRequestSchema: GenMessage<AcceptInvitationRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 3);

/**
 * @generated from message odachin.family.GetFamilyInfoResponse
 */
export type GetFamilyInfoResponse = Message<"odachin.family.GetFamilyInfoResponse"> & {
  /**
   * @generated from field: repeated odachin.family.FamilyUser family_members = 1;
   */
  familyMembers: FamilyUser[];

  /**
   * @generated from field: string family_name = 2;
   */
  familyName: string;

  /**
   * @generated from field: uint64 family_id = 3;
   */
  familyId: bigint;
};

/**
 * Describes the message odachin.family.GetFamilyInfoResponse.
 * Use `create(GetFamilyInfoResponseSchema)` to create a new message.
 */
export const GetFamilyInfoResponseSchema: GenMessage<GetFamilyInfoResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_faimily, 4);

/**
 * @generated from service odachin.family.FamilyService
 */
export const FamilyService: GenService<{
  /**
   * @generated from rpc odachin.family.FamilyService.CreateGroup
   */
  createGroup: {
    methodKind: "unary";
    input: typeof CreateGroupRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.family.FamilyService.GetFamilyInfo
   */
  getFamilyInfo: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetFamilyInfoResponseSchema;
  },
  /**
   * @generated from rpc odachin.family.FamilyService.InviteUser
   */
  inviteUser: {
    methodKind: "unary";
    input: typeof InviteUserRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc odachin.family.FamilyService.AcceptInvitation
   */
  acceptInvitation: {
    methodKind: "unary";
    input: typeof AcceptInvitationRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_odachin_faimily, 0);

