// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file v1/odachin/transaction.proto (package odachin.reward, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/odachin/transaction.proto.
 */
export const file_v1_odachin_transaction: GenFile = /*@__PURE__*/
  fileDesc("Chx2MS9vZGFjaGluL3RyYW5zYWN0aW9uLnByb3RvEg5vZGFjaGluLnJld2FyZCLxAQoZR2V0VHJhbnNhY3Rpb25MaXN0UmVxdWVzdBIcCgpzdGFydF95ZWFyGAEgASgNQgi6SAUqAyjQDxIeCgtzdGFydF9tb250aBgCIAEoDUIJukgGKgQYDCgBEiEKCXN0YXJ0X2RheRgDIAEoDUIJukgGKgQYHygBSACIAQESGgoIZW5kX3llYXIYBCABKA1CCLpIBSoDKNAPEhwKCWVuZF9tb250aBgFIAEoDUIJukgGKgQYDCgBEh8KB2VuZF9kYXkYBiABKA1CCbpIBioEGB8oAUgBiAEBQgwKCl9zdGFydF9kYXlCCgoIX2VuZF9kYXki/gEKD1RyYW5zYWN0aW9uSW5mbxIfCg50cmFuc2FjdGlvbl9pZBgBIAEoBEIHukgEMgIoARIdCgxmcm9tX3VzZXJfaWQYAiABKAlCB7pIBHICEAESGwoKdG9fdXNlcl9pZBgDIAEoCUIHukgEcgIQARIXCgZhbW91bnQYBCABKAVCB7pIBCICIAASIQoQdHJhbnNhY3Rpb25fdHlwZRgFIAEoCUIHukgEcgIQARINCgV0aXRsZRgGIAEoCRITCgtkZXNjcmlwdGlvbhgHIAEoCRIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJXChpHZXRUcmFuc2FjdGlvbkxpc3RSZXNwb25zZRI5ChB0cmFuc2FjdGlvbl9saXN0GAEgAygLMh8ub2RhY2hpbi5yZXdhcmQuVHJhbnNhY3Rpb25JbmZvMoEBChJUcmFuc2FjdGlvblNlcnZpY2USawoSR2V0VHJhbnNhY3Rpb25MaXN0Eikub2RhY2hpbi5yZXdhcmQuR2V0VHJhbnNhY3Rpb25MaXN0UmVxdWVzdBoqLm9kYWNoaW4ucmV3YXJkLkdldFRyYW5zYWN0aW9uTGlzdFJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_timestamp, file_buf_validate_validate]);

/**
 * @generated from message odachin.reward.GetTransactionListRequest
 */
export type GetTransactionListRequest = Message<"odachin.reward.GetTransactionListRequest"> & {
  /**
   * @generated from field: uint32 start_year = 1;
   */
  startYear: number;

  /**
   * @generated from field: uint32 start_month = 2;
   */
  startMonth: number;

  /**
   * @generated from field: optional uint32 start_day = 3;
   */
  startDay?: number;

  /**
   * @generated from field: uint32 end_year = 4;
   */
  endYear: number;

  /**
   * @generated from field: uint32 end_month = 5;
   */
  endMonth: number;

  /**
   * @generated from field: optional uint32 end_day = 6;
   */
  endDay?: number;
};

/**
 * Describes the message odachin.reward.GetTransactionListRequest.
 * Use `create(GetTransactionListRequestSchema)` to create a new message.
 */
export const GetTransactionListRequestSchema: GenMessage<GetTransactionListRequest> = /*@__PURE__*/
  messageDesc(file_v1_odachin_transaction, 0);

/**
 * @generated from message odachin.reward.TransactionInfo
 */
export type TransactionInfo = Message<"odachin.reward.TransactionInfo"> & {
  /**
   * @generated from field: uint64 transaction_id = 1;
   */
  transactionId: bigint;

  /**
   * @generated from field: string from_user_id = 2;
   */
  fromUserId: string;

  /**
   * @generated from field: string to_user_id = 3;
   */
  toUserId: string;

  /**
   * @generated from field: int32 amount = 4;
   */
  amount: number;

  /**
   * @generated from field: string transaction_type = 5;
   */
  transactionType: string;

  /**
   * @generated from field: string title = 6;
   */
  title: string;

  /**
   * @generated from field: string description = 7;
   */
  description: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message odachin.reward.TransactionInfo.
 * Use `create(TransactionInfoSchema)` to create a new message.
 */
export const TransactionInfoSchema: GenMessage<TransactionInfo> = /*@__PURE__*/
  messageDesc(file_v1_odachin_transaction, 1);

/**
 * @generated from message odachin.reward.GetTransactionListResponse
 */
export type GetTransactionListResponse = Message<"odachin.reward.GetTransactionListResponse"> & {
  /**
   * @generated from field: repeated odachin.reward.TransactionInfo transaction_list = 1;
   */
  transactionList: TransactionInfo[];
};

/**
 * Describes the message odachin.reward.GetTransactionListResponse.
 * Use `create(GetTransactionListResponseSchema)` to create a new message.
 */
export const GetTransactionListResponseSchema: GenMessage<GetTransactionListResponse> = /*@__PURE__*/
  messageDesc(file_v1_odachin_transaction, 2);

/**
 * @generated from service odachin.reward.TransactionService
 */
export const TransactionService: GenService<{
  /**
   * @generated from rpc odachin.reward.TransactionService.GetTransactionList
   */
  getTransactionList: {
    methodKind: "unary";
    input: typeof GetTransactionListRequestSchema;
    output: typeof GetTransactionListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_odachin_transaction, 0);

