// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts,import_extension=none"
// @generated from file v1/odachin/odachin.proto (package odachin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcceptInvitationRequest, CreateGroupRequest, CreateUserRequest, CreateUserResponse, DeleteRewardRequest, GetUserInfoRequest, GetUserInfoResponse, InviteUserRequest, LoginRequest, LoginResponse, RegisterAllowanceRequest, RegisterRewardRequest, UpdateAllowanceRequest, UpdateUserRequest } from "./odachin_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service odachin.OdachinService
 */
export const OdachinService = {
  typeName: "odachin.OdachinService",
  methods: {
    /**
     * @generated from rpc odachin.OdachinService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * TODO 未テスト
     *
     * @generated from rpc odachin.OdachinService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.CreateGroup
     */
    createGroup: {
      name: "CreateGroup",
      I: CreateGroupRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.InviteUser
     */
    inviteUser: {
      name: "InviteUser",
      I: InviteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.AcceptInvitation
     */
    acceptInvitation: {
      name: "AcceptInvitation",
      I: AcceptInvitationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.RegisterReward
     */
    registerReward: {
      name: "RegisterReward",
      I: RegisterRewardRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.DeleteReward
     */
    deleteReward: {
      name: "DeleteReward",
      I: DeleteRewardRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.RegisterAllowance
     */
    registerAllowance: {
      name: "RegisterAllowance",
      I: RegisterAllowanceRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.UpdateAllowance
     */
    updateAllowance: {
      name: "UpdateAllowance",
      I: UpdateAllowanceRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.GetUserInfo
     */
    getUserInfo: {
      name: "GetUserInfo",
      I: GetUserInfoRequest,
      O: GetUserInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

