// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=ts,import_extension=none"
// @generated from file odachin.proto (package odachin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, LoginRequest, LoginResponse } from "./odachin_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service odachin.OdachinService
 */
export const OdachinService = {
  typeName: "odachin.OdachinService",
  methods: {
    /**
     * @generated from rpc odachin.OdachinService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc odachin.OdachinService.login
     */
    login: {
      name: "login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

