name: Deploy Frontend to ECR

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-frontend.yml"
    branches:
      - ci-test

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/odachin_web_dev:latest
          docker build -t $IMAGE_URI ./apps/web
          docker push $IMAGE_URI
