name: Integration Test

on:
  workflow_dispatch:
    paths:
      - "apps/service/**"
      - ".github/workflows/service-test.yml"

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # 使用しているGoのバージョンに合わせて調整

      - name: Build and Start Services
        run: |
          docker-compose up postgres -d

      - name: Wait for Services to be Ready
        run: |
          echo "Waiting for services..."
          sleep 30  # DBやEnvoyなどの起動待機。健康チェックができればそちらでもOK

      - name: Run Service Integration Tests
        run: |
          cd apps/service
          go test ./... -v

      - name: Tear down
        if: always()
        run: docker-compose down
